# Generated by Django 5.1.4 on 2024-12-05 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название фильма')),
                ('rating', models.SmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('age_restriction', models.BooleanField(default=False, verbose_name='Наличие возрастного ограничения')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('second_name', models.CharField(max_length=40, verbose_name='Фамилия пользователя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
