# Generated by Django 5.1.4 on 2024-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='cinema.movie', verbose_name='Избранные фильмы'),
        ),
    ]
